import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

info = ctrl.Antecedent(np.arange(0, 101, 1), 'info')
syarat = ctrl.Antecedent(np.arange(0, 101, 1), 'syarat')
petugas = ctrl.Antecedent(np.arange(0, 101, 1), 'petugas')
sarpras = ctrl.Antecedent(np.arange(0, 101, 1), 'sarpras')
kepuasan = ctrl.Consequent(np.arange(0, 401, 1), 'kepuasan')

# variabel info, syarat, petugas, sarpras
for var in [info, syarat, petugas, sarpras]:
    var['Tidak Memuaskan'] = fuzz.trapmf(var.universe, [0, 0, 60, 75])
    var['Cukup Memuaskan'] = fuzz.trimf(var.universe, [60, 75, 90])
    var['Memuaskan'] = fuzz.trapmf(var.universe, [75, 90, 100, 100])

# variabel kepuasan
kepuasan['Tidak Memuaskan'] = fuzz.trapmf(kepuasan.universe, [0, 0, 50, 75])
kepuasan['Kurang Memuaskan'] = fuzz.trapmf(kepuasan.universe, [50, 75, 100, 150])
kepuasan['Cukup Memuaskan'] = fuzz.trapmf(kepuasan.universe, [100, 150, 250, 275])
kepuasan['Memuaskan'] = fuzz.trapmf(kepuasan.universe, [250, 275, 325, 350])
kepuasan['Sangat Memuaskan'] = fuzz.trapmf(kepuasan.universe, [325, 350, 400, 400])

info.view()
syarat.view()
petugas.view()
sarpras.view()
kepuasan.view()
input("Tekan ENTER untuk melanjutkan")

rule1 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Kurang Memuaskan'])
rule2 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule3 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Cukup Memuaskan'])
rule4 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule5 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule6 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Cukup Memuaskan'])
rule7 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule8 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule9 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule10 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule11 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule12 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Cukup Memuaskan'])
rule13 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule14 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule15 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule16 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule17 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule18 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule19 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule20 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule21 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule22 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule23 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule24 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule25 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule26 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule27 = ctrl.Rule(info['Tidak Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule28 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule29 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule30 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Cukup Memuaskan'])
rule31 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule32 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule33 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule34 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule35 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule36 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule37 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule38 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule39 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule40 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule41 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule42 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule43 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule44 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule45 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule46 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule47 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule48 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule49 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule50 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule51 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule52 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule53 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Sangat Memuaskan'])
rule54 = ctrl.Rule(info['Cukup Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule55 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule56 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Cukup Memuaskan'])
rule57 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule58 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule59 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule60 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule61 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule62 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule63 = ctrl.Rule(info['Memuaskan'] & syarat['Tidak Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule64 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Cukup Memuaskan'])
rule65 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule66 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Memuaskan'])
rule67 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule68 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule69 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule70 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule71 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Sangat Memuaskan'])
rule72 = ctrl.Rule(info['Memuaskan'] & syarat['Cukup Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule73 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule74 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Memuaskan'])
rule75 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Tidak Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule76 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Memuaskan'])
rule77 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Sangat Memuaskan'])
rule78 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Cukup Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])
rule79 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Tidak Memuaskan'], kepuasan['Sangat Memuaskan'])
rule80 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Cukup Memuaskan'], kepuasan['Sangat Memuaskan'])
rule81 = ctrl.Rule(info['Memuaskan'] & syarat['Memuaskan'] & petugas['Memuaskan'] & sarpras['Memuaskan'], kepuasan['Sangat Memuaskan'])

sistem_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19, rule20, rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30, rule31, rule32, rule33, rule34, rule35, rule36, rule37, rule38, rule39, rule40, rule41, rule42, rule43, rule44, rule45, rule46, rule47, rule48, rule49, rule50, rule51, rule52, rule53, rule54, rule55, rule56, rule57, rule58, rule59, rule60, rule61, rule62, rule63, rule64, rule65, rule66, rule67, rule68, rule69, rule70, rule71, rule72, rule73, rule74, rule75, rule76, rule77, rule78, rule79, rule80, rule81])
sistem_sim = ctrl.ControlSystemSimulation(sistem_ctrl)

def prediksi_kepuasan(info, syarat, petugas, sarpras):
    sistem_sim.input['info'] = info
    sistem_sim.input['syarat'] = syarat
    sistem_sim.input['petugas'] = petugas
    sistem_sim.input['sarpras'] = sarpras

    sistem_sim.compute()
    return sistem_sim.output['kepuasan']

if __name__ == '__main__':
    nilai = prediksi_kepuasan(info=80, syarat=60, petugas=50, sarpras=90)
    print(f"Nilai Kepuasan: {nilai:.2f}")
    kepuasan.view(sim=sistem_sim)
    input("Tekan ENTER untuk melanjutkan")
